---
title: "Good Software Engineering Practice for R Packages"
---

<!--
Creators (initial authors): 
- Daniel Sabanes Bove, https://github.com/danielinteractive/ and www.linkedin.com/in/danielsabanesbove/
- Friedrich Pahlke, https://github.com/fpahlke/ and www.linkedin.com/in/pahlke/
- Kevin Kunzmann, https://github.com/kkmann/ and https://www.linkedin.com/in/kevin-kunzmann-6486a11bb/
In the current version, changes were done by (later authors):
- Liming Li, https://github.com/clarkliming
- Joe Zhu, https://github.com/shajoezhu and http://www.linkedin.com/in/joe-zhu-464b5818
License: This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.
To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.
The source files are hosted at https://github.com/pharmarug/pharmasug2026-r-workshop, which is forked from
the original version at https://github.com/openpharma/workshop-r-swe.
Important: To use this work you must provide the name of the creators (initial authors), a link to the material, a link to the license, and indicate if changes were made.
--> 

Welcome to the homepage of the workshop *"Good Software Engineering Practice for R Packages"*. In this course participants will learn hands-on skills and tools to engineer reliable R packages used in biostatistics. The day will be a mix of presentations and exercises. Participants need to be comfortable with writing functions in R and use their own laptops.

## Up-coming Event

The next event will be on-site, at the Radisson Collection Hotel, Yangtze Shanghai, on 23rd July 2026.

Please note that all the content will be in English, delivered in English and Chinese. 
This event is sponsored/organized by PharmaSUG and advertised also through
the R User Group (RUG) China. Presenters will be Shuang Li, Wenyi Liu and Joe Zhu.

## Workshop Program

This is the program for 23rd July 2026, all times in China Standard Time (GMT+8):

```{r}
#| echo: false
readr::read_csv("slides/resources/program.csv", col_types = "cc") |>
  knitr::kable(col.names = c("", ""))
```

## Prerequisites & Technical Setup

Prior to the course, participants should

-   set up a (free) [GitHub.com account](https://github.com/join). There are other git Platforms like [Gitlab](https://about.gitlab.com/) or [Bitbucket](https://bitbucket.org/) but we made the choice to go with GitHub.com for the course since it is by far the most relevant git platform in the R community.
-   download and extract [simulatr.zip](slides/download/simulatr.zip)
-   either make sure they have a working R software development setup on their own laptop (up-to-date git/Rtools/R/RStudio) or get access to <https://posit.cloud>. The latter offers a free tier account with 25 hours of computing time per months and can be accessed using ones GitHub.com account.
-   in your rstudio terminal, set the ssh key by `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`, then use command `cat ~/.ssh/id_rsa.pub` to show your public key, and copy and paste it to https://github.com/settings/keys, with the name "pharmasug-2026-key".

For the course, participants are required to use their own laptop to be able to participate in the exercises.

### Optional reading list

-   Excellent and very comprehensive [R Packages (2e)](https://r-pkgs.org/)
-   (Hardcore) description of how [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html) works
-   [GitHub 'Hello World'](https://docs.github.com/en/get-started/quickstart/hello-world) tutorial on how to use GitHub.com (does not require git command line knowledge)
-   Tutorial on [version control with git and SVN](https://support.posit.co/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN) (we will be using git)
-   Command line git mini intro [trygit](https://trygit.js.org/)
-   [first steps with git & github by RStudio](https://www.youtube.com/watch?v=jN6tvgt3GK8)
-   [RStudio cheatsheets/ Git & GitHub](https://github.com/rstudio/cheatsheets/blob/main/git-github.pdf)

## Past Events

- 31st July 2025, Shanghai
- 1st August 2024, Beijing
- 24th March 2023, Shanghai
- 10th February 2023, Basel
